### ISSUE TITLE
tara_launch failed

### ISSUE THREAD

**Issue by Changliu52** [dilipkumar25/see3cam#11]
Just updated to master source.
But when I run: `roslaunch uvc_camera tara_launch.launch`
It fails with the
[ERROR] [1507834258.902240361]: Tried to advertise a service that is already advertised in this node [/stereo/set_camera_info]
terminate called after throwing an instance of 'std::runtime_error'
  what():  pixel format unavailable

details below: (console output)
... logging to /home/chang/.ros/log/47bc5652-af7e-11e7-99f5-2816add270e4/roslaunch-chang-2092.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://chang:34543/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /stereo/uvc_camera/cameraLeft_info_url: file://${ROS_HOME...
 * /stereo/uvc_camera/cameraRight_info_url: file://${ROS_HOME...
 * /stereo/uvc_camera/device: /dev/video0
 * /stereo/uvc_camera/exposureValue: 1
 * /stereo/uvc_camera/fps: 30
 * /stereo/uvc_camera/frame: webcam
 * /stereo/uvc_camera/height: 480
 * /stereo/uvc_camera/width: 640

NODES
  /stereo/
    uvc_camera (uvc_camera/tara_node)

auto-starting new master
process[master]: started with pid [2143]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 47bc5652-af7e-11e7-99f5-2816add270e4
process[rosout-1]: started with pid [2156]
started core service [/rosout]
process[stereo/uvc_camera-2]: started with pid [2159]
[ERROR] [1507834258.902240361]: Tried to advertise a service that is already advertised in this node [/stereo/set_camera_info]
terminate called after throwing an instance of 'std::runtime_error'
  what():  pixel format unavailable
================================================================================REQUIRED process [stereo/uvc_camera-2] has died!
process has died [pid 2159, exit code -6, cmd /home/chang/catkin_ws/devel/lib/uvc_camera/tara_node __name:=uvc_camera __log:=/home/chang/.ros/log/47bc5652-af7e-11e7-99f5-2816add270e4/stereo-uvc_camera-2.log].
log file: /home/chang/.ros/log/47bc5652-af7e-11e7-99f5-2816add270e4/stereo-uvc_camera-2*.log
Initiating shutdown!
================================================================================
[stereo/uvc_camera-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Changliu52** [comment]
Looks like it works with usb3. But on usb2 I can still access the camera using guvcview.

**Comment by eirikaso** [comment]
Hi
I'm getting the same error and I'm using USB3. It's working with guvcview.

Is this working fine on your setup now or do you have any tips?
