### ISSUE TITLE
/stereo/get_IMU output standard sensor_msgs/Imu message

### ISSUE THREAD

**Issue by Changliu52** [dilipkumar25/see3cam#3]
Dear developer,

I just bought a tara camera and using is with ros in odroid xu4.
I found that the /stereo/get_IMU topic only output accelerometer data, but it also has a gyroscope right?

I wonder if you can update this package to output standard sensor_msgs/Imu as defined in http://docs.ros.org/jade/api/sensor_msgs/html/msg/Imu.html

This must be very useful for deploying the camera with the standard visual-inertial odometry system.

Many thanks.

Chang

**Comment by jasperdev** [comment]
I can second that the  sensor_msgs/Imu format would be very useful. Is this possible?

**Comment by dilipkumar25** [comment]
Hi,

Thanks for pointing it out. We are looking into your request. Will update the code when it is complete.

Thank You,
Dilip Kumar

**Comment by dilipkumar25** [comment]
Hi,

Your request has been implemented. Check the master branch or tag "tara_v1.3" for the update

**Comment by Changliu52** [comment]
Thank you so much for the quick update. I will try this out as soon as possible.

**Comment by jasperdev** [comment]
looks good, thanks!
