### ISSUE TITLE
Stereo Node launch fails - cannot acces video device 1

### ISSUE THREAD

**Issue by antoan** [dilipkumar25/see3cam#8]
From your readme: "Creates a stereo image node pair (left/image_raw and right/image_raw) from any connected Tara devices."

The stereo launch file stereo_node.launch attempts to access video devices 0 and 1:

<param name="left/device" type="string" value="/dev/video0" />
<param name="right/device" type="string" value="/dev/video1" />

I'm not sure how this can ever work since whenever the Tara sensor is connected udev only  ever 'sees' a single video device: 

>v4l2-ctl --list-devices
See3CAM_Stereo (usb-0000:03:00.0-1):
	/dev/video0

**Comment by dilipkumar25** [comment]
Hi @antoan,

You are using the wrong launch file to access the Tara camera. You should use the "tara_launch.launch" file that is provided along with other launch files. 

For more info on how to use the Tara camera in ROS, check this [article](https://www.e-consystems.com/Articles/Camera/ros-support-for-tara.asp)

**Comment by antoan** [comment]
Hi there, I am ware of this, this is the launchfile I had been using all along. 

I was essentially experimenting while trying to solve a separate unrelated issue I raised here, which is holding me up at the moment.
 https://github.com/dilipkumar25/see3cam/issues/9

**Comment by dilipkumar25** [comment]
Hi @antoan ,

I'm closing out this issue as there are no action items pending here. I have responded to your other issue separately.

**Comment by antoan** [comment]
That's fine, I will prepare a detailed response for my other issue soon - I've been quite pressed for time.
